// Generated by CoffeeScript 1.9.0
(function() {
  var BookmarkView,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __hasProp = {}.hasOwnProperty,
    __slice = [].slice;

  BookmarkView = (function(_super) {
    var _template;

    __extends(BookmarkView, _super);

    _template = null;

    function BookmarkView() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      _template = _.template("");
      BookmarkView.__super__.constructor.apply(this, args);
    }

    return BookmarkView;

  })(Backbone.View);

}).call(this);
