// Generated by CoffeeScript 1.9.0
(function() {
  var define, require,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define = $.fn.select2.amd.define;

  require = $.fn.select2.amd.require;

  define('select2/i18n/ru', [], function() {
    return {
      errorLoading: function() {
        return "Нельзя отобразить результаты поиска.";
      },
      inputTooLong: function(args) {
        var message, overChars;
        overChars = args.input.length - args.maximum;
        return message = "Количество символов в строке превышена на: " + overChars + " ";
      },
      inputTooShort: function() {
        return "Слишком короткая строка поиска";
      },
      loadingMore: function() {
        return 'Загрузка результатов...';
      },
      maximumSelected: function(args) {
        return "Выможете выбрать максимум " + args.maximum + " пунктов";
      },
      noResults: function() {
        return "Ничего не найдено";
      },
      searching: function() {
        return "Поиск...";
      }
    };
  });

  $.fn.select2.defaults.set('language', require('select2/i18n/ru'));

  window.ui = _.extend(window.ui || {}, {
    ComicsSelector: null
  });

  window.ui.ComicsSelector = (function() {
    var _searchIconTemplate;

    _searchIconTemplate = _.template('<span class="fa fa-search"></span>');

    ComicsSelector.prototype._selector = '';

    ComicsSelector.prototype._toolbarSelector = null;

    ComicsSelector.prototype.select2 = null;

    ComicsSelector.prototype.$el = null;

    ComicsSelector.prototype.$toolbar = null;

    ComicsSelector.prototype.$go = null;

    function ComicsSelector(_at__toolbarSelector, _at__selector) {
      this._toolbarSelector = _at__toolbarSelector;
      this._selector = _at__selector;
      this._updateTemplate = __bind(this._updateTemplate, this);
      this._closeing = __bind(this._closeing, this);
      this._open = __bind(this._open, this);
      this.value = __bind(this.value, this);
      this.go = __bind(this.go, this);
      this.$toolbar = $(this._toolbarSelector);
      this.$go = $('#go');
      this.$go.click(this.go);
      this.$el = $(this._selector).eq(0);
      $(window).load((function(_this) {
        return function() {
          _this.select2 = _this.$el.data('select2');
          _this.$el.on('select2:open', _this._open).on('select2:closing', _this._closeing);
          return _this._updateTemplate();
        };
      })(this));
    }

    ComicsSelector.prototype.go = function(e) {
      return $(this).trigger('go', [this.$el.val()]);
    };

    ComicsSelector.prototype.value = function(val) {
      if (val != null) {
        return this.$el.val(val).trigger('change');
      } else {
        return this.$el.val();
      }
    };

    ComicsSelector.prototype._open = function(e) {
      return this.select2.$results.parents('.select2-results').mCustomScrollbar("destroy").mCustomScrollbar({
        theme: 'dark-2',
        axis: 'y'
      });
    };

    ComicsSelector.prototype._closeing = function(e) {
      return this.select2.$results.parents('.select2-results').mCustomScrollbar("destroy");
    };

    ComicsSelector.prototype._updateTemplate = function() {
      var $search;
      $search = this.select2.dropdown.$searchContainer;
      $search.append(_searchIconTemplate({}));
      return this.select2.$results.unmousewheel();
    };

    return ComicsSelector;

  })();

}).call(this);
