// Generated by CoffeeScript 1.9.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  window.tools = _.extend(window.tools || {}, {
    ComicsView: null
  });

  window.tools.LoadingBox = (function() {
    var _alt, _image, _loadingBox, _template;

    _image = null;

    _alt = "";

    _template = _.template('<img src="{{ src }}" alt="">');

    _loadingBox = null;

    LoadingBox.prototype.selector = '';

    function LoadingBox(_at_selector) {
      this.selector = _at_selector;
      this.setImage = __bind(this.setImage, this);
      _loadingBox = $(this.selector);
    }

    LoadingBox.prototype.setImage = function(src) {
      if ((_loadingBox != null) && _loadingBox.length) {
        _image = _template({
          src: src
        });
        _image.on('load', (function(_this) {
          return function() {
            return $(_this).trigger('load');
          };
        })(this));
        _loadingBox.append(_image);
        return $(this).trigger('start');
      }
    };

    LoadingBox.prototype.getImage = function() {
      return _image;
    };

    LoadingBox.prototype.setAlt = function(alt) {
      return _image.attr('alt', alt);
    };

    LoadingBox.prototype.reset = function() {
      return _image = null;
    };

    return LoadingBox;

  })();

}).call(this);
