// Generated by CoffeeScript 1.9.0
(function() {
  var Top;

  Top = (function() {
    function Top() {
      this.controller();
    }

    Top.prototype.controller = function() {
      return $(function() {
        return $('[data-plugin="top"]').click((function(_this) {
          return function() {
            return $("html, body").animate({
              'scrollTop': 0
            });
          };
        })(this));
      });
    };

    return Top;

  })();

  new Top;

}).call(this);
